"""Split port/gen/recomp_funcs.c into several translation units for clang.

allegrexrecomp writes the game's code as one ~200 MB C file. MSVC compiles it
function by function; clang keeps a whole translation unit in memory while it
optimises and runs out of memory on it (seen with 32 GB). Here the file is cut
at the banners that start each function, into N parts that compile alone:

  - the file-static items (psp_body_*, psp_step_*, psp_orig_*, psp_scc_step and
    the variable psp_scc_next) become external, declared in recomp_split.h;
  - psp_scc_drain, a two-line helper, becomes a static inline in that header;
  - part 0 defines psp_scc_next.

Nothing else changes, so the parts behave exactly as the single file does.

  python split_gen.py <recomp_funcs.c> <out dir> [parts]

The output is rewritten only when the input is newer than it.
"""

import os
import re
import sys

BANNER = '/* ---------------------------------------------------------------'
STATIC_DEF = re.compile(r'^static (void psp_(?:body|step|orig)_[0-9A-F]{8}\([^)]*\))')
# external functions defined in the file but declared only there (psp_at_*, the
# label entry points), which other parts may name
EXTERN_DEF = re.compile(r'^(void psp_[a-z]+_[0-9A-F]{8}\([^)]*\))\s*\{')


def main():
    src, out = sys.argv[1], sys.argv[2]
    parts = int(sys.argv[3]) if len(sys.argv) > 3 else 24
    stamp = os.path.join(out, 'recomp_split.h')
    if os.path.exists(stamp) and os.path.getmtime(stamp) >= os.path.getmtime(src):
        print('split_gen: up to date')
        return
    os.makedirs(out, exist_ok=True)
    with open(src, 'r', encoding='utf-8', newline='') as f:
        lines = f.read().split('\n')

    first = next(i for i, l in enumerate(lines) if l.startswith(BANNER))
    preamble, body = lines[:first], lines[first:]
    for l in preamble:                      # what this script knows how to move into the header
        if l.startswith('static ') and not (l.startswith('static uint32_t psp_scc_next;') or
                                            l.startswith('static void psp_scc_step(') or
                                            l.startswith('static void psp_scc_drain(')):
            sys.exit('split_gen: unexpected file-static item in the preamble: ' + l)

    protos = []
    for i, l in enumerate(body):
        if l.startswith('static void psp_scc_step(uint32_t t);'):
            body[i] = ''                    # the forward declaration: in the header now
            continue
        m = STATIC_DEF.match(l)
        if m:
            protos.append(m.group(1) + ';')
            body[i] = l[len('static '):]
        elif EXTERN_DEF.match(l):
            protos.append(EXTERN_DEF.match(l).group(1) + ';')
        elif l.startswith('static void psp_scc_step('):
            body[i] = l[len('static '):]
        elif l.startswith('static ') :
            sys.exit('split_gen: unexpected file-static item: ' + l[:100])

    with open(stamp + '.tmp', 'w', encoding='utf-8', newline='\n') as h:
        h.write('/* Generated by port/android/split_gen.py from recomp_funcs.c -- do not edit. */\n')
        h.write('#ifndef RECOMP_SPLIT_H\n#define RECOMP_SPLIT_H\n#include "recomp_funcs.h"\n\n')
        h.write('extern uint32_t psp_scc_next;   /* a pending tail transfer within a tail-call cycle */\n')
        h.write('void psp_scc_step(uint32_t t);\n')
        h.write('static inline void psp_scc_drain(void) {\n'
                '    while (psp_scc_next) { const uint32_t t_ = psp_scc_next; psp_scc_next = 0; psp_scc_step(t_); }\n'
                '}\n\n')
        h.write('\n'.join(protos))
        h.write('\n\n#endif\n')

    starts = [i for i, l in enumerate(body) if l.startswith(BANNER)]
    per = max(1, len(starts) // parts)
    cuts = [starts[k] for k in range(0, len(starts), per)][:parts] + [len(body)]
    for p in range(len(cuts) - 1):
        with open(os.path.join(out, 'recomp_part_%02d.c' % p), 'w', encoding='utf-8', newline='\n') as f:
            f.write('/* Part %d of recomp_funcs.c (port/android/split_gen.py) -- do not edit. */\n' % p)
            f.write('#include "recomp_split.h"\n\n')
            if p == 0:
                f.write('uint32_t psp_scc_next;\n\n')
            f.write('\n'.join(body[cuts[p]:cuts[p + 1]]))
            f.write('\n')
    for stale in os.listdir(out):           # parts left over from a run with more parts
        m = re.match(r'recomp_part_(\d+)\.c$', stale)
        if m and int(m.group(1)) >= len(cuts) - 1:
            os.remove(os.path.join(out, stale))
    os.replace(stamp + '.tmp', stamp)
    print('split_gen: %d functions, %d prototypes, %d parts' % (len(starts), len(protos), len(cuts) - 1))


if __name__ == '__main__':
    main()
